---

- name: Configure new devices
  hosts: unconfigured
  roles:
    - common
    - mdns

- name: Install/Update configured devices
  hosts: configured
  roles:
    - serialcom

  tasks:
  - name: Install base packages
    ansible.builtin.apt:
      name:
        - vim-tiny
        - git
      state: present
      update_cache: "yes"
    become_method: sudo
    become: true
